[tool.black]
line-length = 120
skip-string-normalization = true
target-version = ['py38']

[tool.isort]
line_length=120
default_section = "THIRDPARTY"
known_first_party = ["analysis", "compare", "helperFunctions", "install", "intercom", "objects", "plugins", "scheduler",
    "statistic", "storage", "test", "unpacker", "version", "web_interface"]
known_third_party = "docker"
profile = "black"
