[project]
name = "fact-extractor"
version = "0.3.0"
requires-python = ">=3.11"
dependencies = [
    "distro",
    "common_helper_process @ git+https://github.com/fkie-cad/common_helper_process.git",
    # server mode
    "flask==3.1.3",
    "flask-restful==0.3.10",
    "gunicorn==26.0.0",
    # unpackers
    "pluginbase==1.0.1",  # FixMe: deprecated
    "common_helper_unpacking_classifier @ git+https://github.com/fkie-cad/common_helper_unpacking_classifier.git@0.7.0",
    "python-magic==0.4.27",
    "patool==4.0.5",
    # jffs2
    "jefferson==0.4.7",
    # ubi
    "ubi-reader==0.8.13",
    # dji / dlink_shrs
    "pycryptodome==3.23.0",
    # hp / raw
    "common_helper_extraction @ git+https://github.com/fkie-cad/common_helper_extraction.git",
    # intel_hex
    "intelhex==2.3.0",
    # linuxkernel
    "lz4==4.4.5",
    # FixMe: this has also a dependency to a package called python-lzo (name conflict with python-lzo from jefferson)
    "vmlinux_to_elf @ git+https://github.com/marin-m/vmlinux-to-elf.git",
    # mikrotik
    "npkPy==2021.10.22.15.58",
    # sevenz
    "common_helper_passwords @ git+https://github.com/fkie-cad/common_helper_passwords.git",
    # srec
    "bincopy==20.1.1",
    # uboot
    "extract-dtb==1.2.3",
    # uefi
    "uefi-firmware==1.11",
    "pylibfdt==1.7.2.post1",
    # xiaomi hdr
    "structlog==25.5.0",
    # unblob
    "unblob==26.3.30",
]

[project.optional-dependencies]
dev = [
    "pytest==9.0.3",
    "pytest-cov==7.1.0",
    "testresources==2.1.2",
]

[project.scripts]
fact-extractor = "fact_extractor.cli:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["fact_extractor"]

[tool.ruff]
extend-exclude = [
    "bin",
    "fact_extractor/plugins/unpacking/*/test/data/*",
]
line-length = 120
target-version = "py311"

[tool.ruff.lint]
select = [
    "F",  # Pyflakes
    "E",  # pycodestyle Error
    "W",  # pycodestyle Warning
    "C90",  # mccabe
    "I",  # isort
    "N",  # pep8-naming
    "UP",  # pyupgrade
    "B",  # flake8-bugbear
    "A",  # flake8-builtins
    "C4",  # flake8-comprehensions
    "EXE",  # flake8-executable
    "FA",  # flake8-future-annotations
    "ISC",  # flake8-implicit-str-concat
    "PIE",  # flake8-pie
    "T20",  # flake8-print
    "PT",  # flake8-pytest-style
    "Q",  # flake8-quotes
    "RET",  # flake8-return
    "SIM",  # flake8-simplify
    "TCH",  # flake8-type-checking
    "ARG",  # flake8-unused-arguments
    "PTH",  # flake8-use-pathlib
    "ERA",  # eradicate
    "PL",  # Pylint
    "PERF",  # Perflint
    "RUF",  # Ruff-specific rules
]
ignore = [
    "A003",
    "PERF203",
    "PERF401",
    "RUF001",
    "RUF002",
    "RUF003",
    "RUF015",
    # pydantic only supports these from python>=3.9
    "UP006",
    "UP007",
    # rules may cause conflicts when used with the formatter
    "ISC001",
    "Q001",
]
fixable = ["ALL"]

[tool.ruff.lint.per-file-ignores]
"test*.py" = ["ARG001", "ARG002", "PLR2004"]
"conftest.py" = ["ARG002"]

[tool.ruff.lint.isort]
known-first-party = ["config", "helperFunctions", "install", "plugins", "test", "unpacker", "version"]

[tool.ruff.lint.pylint]
max-args=7
max-public-methods = 40

[tool.ruff.lint.mccabe]
max-complexity = 10

[tool.ruff.lint.flake8-pytest-style]
fixture-parentheses = false

[tool.ruff.lint.flake8-quotes]
inline-quotes = "single"
multiline-quotes = "single"
docstring-quotes = "double"

[tool.ruff.format]
quote-style = "single"

[tool.pyrefly]
search_path = ["fact_extractor"]
