name: Build CI
run-name: Build CI
on:
  pull_request:
    branches: [ master ]
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:

jobs:
  build-ci:
    runs-on: [ self-hosted, linux, x64, jammy ]
    timeout-minutes: 45
    steps:
      - name: Add Masks
        run: |
          echo "::add-mask::${{ secrets.NETWORK_MASK_1 }}"
          echo "::add-mask::${{ secrets.NETWORK_MASK_2 }}"
          echo "::add-mask::${{ secrets.NETWORK_MASK_3 }}"
          echo "::add-mask::${{ secrets.INTERNAL_NODE_1 }}"
          echo "::add-mask::${{ secrets.INTERNAL_NODE_2 }}"
          echo "::add-mask::${{ secrets.INTERNAL_NODE_3 }}"
          echo "::add-mask::${{ secrets.INTERNAL_NODE_4 }}"
          echo "::add-mask::${{ secrets.INTERNAL_NODE_5 }}"
          echo "::add-mask::${{ secrets.INTERNAL_NODE_6 }}"
          echo "::add-mask::${{ secrets.INTERNAL_NODE_7 }}"
          echo "::add-mask::${{ secrets.INTERNAL_NODE_8 }}"
          echo "::add-mask::${{ secrets.SECRET_STRING_1 }}"
          echo "::add-mask::${{ secrets.SECRET_STRING_2 }}"
          echo "::add-mask::${{ secrets.SECRET_STRING_3 }}"
      - name: Checkout Branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
      - name: Set ulimit
        run: ulimit -n 9999
      - name: Pre-Installation
        shell: 'script -q -e -c "bash {0}"'
        run: ./fact_extractor/install/pre_install.sh
      - name: Install fact_extractor
        shell: 'script -q -e -c "bash {0}"'
        run: ./fact_extractor/install.py
      - name: Unit Tests
        shell: 'script -q -e -c "bash {0}"'
        run: pytest
